[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
deposit_program = "Bf4qyNgbkoSUsxAQakj9iqp7GApdnT6qJWLikDzK9Rqn"

[programs.localnet]
deposit_program = "Bf4qyNgbkoSUsxAQakj9iqp7GApdnT6qJWLikDzK9Rqn"

[programs.mainnet]
deposit_program = "Bf4qyNgbkoSUsxAQakj9iqp7GApdnT6qJWLikDzK9Rqn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm jest --preset ts-jest"
