[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
deposit_program = "EkUjnEsQygT5KJizKHEGPyjP2amfRQutMuA8pTea8TQq"

[programs.localnet]
deposit_program = "EkUjnEsQygT5KJizKHEGPyjP2amfRQutMuA8pTea8TQq"

[programs.mainnet]
deposit_program = "EkUjnEsQygT5KJizKHEGPyjP2amfRQutMuA8pTea8TQq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm jest --preset ts-jest"
