[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
deposit_program = "DxWhmvfUXfbPrakjq25UFM1mXk1RuqEfgnfC9fvyXrkw"

[programs.localnet]
deposit_program = "DxWhmvfUXfbPrakjq25UFM1mXk1RuqEfgnfC9fvyXrkw"

[programs.mainnet]
deposit_program = "DxWhmvfUXfbPrakjq25UFM1mXk1RuqEfgnfC9fvyXrkw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm jest --preset ts-jest"
